### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by HFsi** [RobotDynOfficial/RBDDimmer#19]
I´m getting a bunch of errors while compiling, like....

sketch\SerialMonitorDim.ino.cpp.o:(.text.setup+0x14): undefined reference to `dimmerLamp::begin(DIMMER_MODE_typedef, ON_OFF_typedef)'

and a lot more of undefined references

**Comment by HFsi** [comment]
I was compiling for Arduino, not ESP8266

**Comment by benoit-cty** [comment]
In my case it was because I put only the content of `src` folder in the `librairies` folder.
